In [1]:
import pandas

In [2]:
import os

In [3]:
import os
import pandas as pd

csv_directory = "csvs"

csv_files = [file for file in os.listdir(csv_directory) if file.endswith('.csv')]

#Initially all columns are uploaded as string to prevent upload error and parsing issues.
csv_dataframes = {}
for file in csv_files:
    file_path = os.path.join(csv_directory, file)
    try:
        csv_dataframes[file] = pd.read_csv(file_path, dtype=str, engine='python')
        print(f"Uploaded: {file}")
    except pd.errors.ParserError as e:
        print(f"Error reading {file}: {e}")

Uploaded: top50-youtubers-wiki.csv
Uploaded: UUX6OQ3DkcsbYNE6H8uQQuVA_videos.csv
Uploaded: UUq-Fj5jknLsUf-MWSy4_brA_videos.csv
Uploaded: UUbCmjCuTUZos6Inko4u57UQ_videos.csv
Uploaded: top50_channels.csv

In [26]:
top50_wiki = csv_dataframes['top50-youtubers-wiki.csv']

In [27]:
top50_wiki

,Name,Link,Brand Channel,Subscribers (millions),Primary Language,Category,Country
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,MrBeast,Link,No,317,English,Entertainment[20],United States
2,T-Series,Link,Yes,274,Hindi[21][22],Music,India
3,Cocomelon - Nursery Rhymes,Link,Yes,183,English,Education,United States
4,SET India,Link,Yes,178,Hindi[23],Entertainment,India
5,Kids Diana Show,Link,Yes,126,English[24],Entertainment,United States/ Ukraine
6,Vlad and Niki,Link,No,125,English,Entertainment,Russia/ United States
7,Like Nastya,Link,No,120,English,Entertainment,Russia/ United States
8,PewDiePie,Link,No,111,English,Entertainment,Sweden/ Japan/ United States[a]
9,Zee Music,Link,Yes,110,Hindi[25][26],Music,India
10,WWE,Link,Yes,104,English,Sports,United States
11,Goldmines,Link,Yes,100,Hindi,Film,India
12,Sony SAB,Link,Yes,95.8,Hindi,Entertainment,India
13,Blackpink,Link,No,94.8,Korean,Music,South Korea
14,ChuChu TV Nursery Rhymes & Kids Songs,Link,Yes,93.2,Hindi[27],Education,India
15,Stokes Twins,Link,No,89.9,English,Entertainment,United States
16,Zee TV,Link,Yes,84.2,Hindi,Entertainment,India
17,5-Minute Crafts,Link,Yes,80.9,English,How-to,Cyprus[b]
18,BANGTANTV,Link,No,79,Korean,Music,South Korea
19,Pinkfong,Link,Yes,77.8,English,Education,South Korea
20,Colors TV,Link,Yes,76.1,Hindi,Entertainment,India
21,Hybe Labels,Link,Yes,75.7,Korean,Music,South Korea
22,Justin Bieber,Link,No,73.6,English,Music,Canada
23,T-Series Bhakti Sagar,Link,Yes,70.2,Hindi,Music,India
24,Shemaroo Filmi Gaane,Link,Yes,69.5,Hindi,Music,India
25,Tips Official,Link,Yes,69,Hindi,Entertainment,India
26,Aaj Tak,Link,Yes,67.4,Hindi,News,India
27,Canal KondZilla,Link,Yes,67.3,Portuguese,Music,Brazil
28,A4,Link,No,67.3,Russian,Entertainment,Belarus
29,El Reino Infantil,Link,Yes,66,Spanish,Music,Argentina
30,Infobells - Hindi,Link,Yes,64.7,Hindi,Education,India
31,ZAMZAM ELECTRONICS TRADING,Link,No,64.7,Arabic,Entertainment,United Arab Emirates
32,UR Cristiano,Link,No,63.1,"Portuguese, English",Entertainment/Sports,Portugal
33,Wave Music,Link,Yes,62.9,Bhojpuri,Music,India
34,Toys and Colors,Link,No,62.9,English,Entertainment,United States
35,Movieclips,Link,Yes,62.2,English,Film,United States
36,Eminem Music,Link,No,61.9,English,Music,United States
37,Sony Music India,Link,Yes,61.9,Hindi,Music,India
38,YRF,Link,Yes,61.8,Hindi,Music,India
39,Dude Perfect,Link,No,60.4,English,Comedy,United States
40,Taylor Swift,Link,No,60,English,Music,United States
41,HAR PAL GEO,Link,Yes,59.8,Urdu,Entertainment,Pakistan
42,김프로KIMPRO,Link,No,59.1,Korean,Entertainment,South Korea
43,Alan Chikin Chow,Link,No,59.1,English,Entertainment,United States
44,LooLoo Kids,Link,Yes,58.1,English,Music,Romania
45,Marshmello,Link,No,57.4,English,Music,United States
46,ARY Digital HD,Link,Yes,57.4,Urdu,Entertainment,Pakistan
47,BillionSurpriseToys,Link,Yes,57.3,English,Entertainment,United States
48,Mark Rober,Link,No,57.2,English,Education/Entertainment,United States
49,Fede Vigevani,Link,No,56.5,Spanish,Entertainment,Mexico
50,KL BRO Biju Rithvik,Link,No,56.1,Hindi,Vlogging,India

In [28]:
#Dropping the first row because it contains NaN
top50_wiki= top50_wiki.drop(0)

In [30]:
top50_wiki = top50_wiki.drop(['Subscribers (millions)', 'Link'], axis=1)

In [42]:
#Now we are ready for data cleaning.
# '/' will be replaced with ','
#Unnecessary characters and numbers will be removed.

In [32]:
#Remove square brackets and numbers from the 'Primary Language' column
top50_wiki['Primary Language'] = top50_wiki['Primary Language'].str.replace(r'[\[\]0-9]', '', regex=True)

In [36]:
# Remove numbers and square brackets from the 'Category' column
top50_wiki['Category'] = top50_wiki['Category'].str.replace(r'\[\d+\]', '', regex=True)

top50_wiki['Category'] = top50_wiki['Category'].str.replace('/', ',', regex=False)

In [40]:
top50_wiki['Country'] = top50_wiki['Country'].str.replace('/', ',', regex=False)
top50_wiki['Country'] = top50_wiki['Country'].str.replace(r'\[.*?\]', '', regex=True)

In [41]:
top50_wiki

,Name,Brand Channel,Primary Language,Category,Country
1,MrBeast,No,English,Entertainment,United States
2,T-Series,Yes,Hindi,Music,India
3,Cocomelon - Nursery Rhymes,Yes,English,Education,United States
4,SET India,Yes,Hindi,Entertainment,India
5,Kids Diana Show,Yes,English,Entertainment,"United States, Ukraine"
6,Vlad and Niki,No,English,Entertainment,"Russia, United States"
7,Like Nastya,No,English,Entertainment,"Russia, United States"
8,PewDiePie,No,English,Entertainment,"Sweden, Japan, United States"
9,Zee Music,Yes,Hindi,Music,India
10,WWE,Yes,English,Sports,United States
11,Goldmines,Yes,Hindi,Film,India
12,Sony SAB,Yes,Hindi,Entertainment,India
13,Blackpink,No,Korean,Music,South Korea
14,ChuChu TV Nursery Rhymes & Kids Songs,Yes,Hindi,Education,India
15,Stokes Twins,No,English,Entertainment,United States
16,Zee TV,Yes,Hindi,Entertainment,India
17,5-Minute Crafts,Yes,English,How-to,Cyprus
18,BANGTANTV,No,Korean,Music,South Korea
19,Pinkfong,Yes,English,Education,South Korea
20,Colors TV,Yes,Hindi,Entertainment,India
21,Hybe Labels,Yes,Korean,Music,South Korea
22,Justin Bieber,No,English,Music,Canada
23,T-Series Bhakti Sagar,Yes,Hindi,Music,India
24,Shemaroo Filmi Gaane,Yes,Hindi,Music,India
25,Tips Official,Yes,Hindi,Entertainment,India
26,Aaj Tak,Yes,Hindi,News,India
27,Canal KondZilla,Yes,Portuguese,Music,Brazil
28,A4,No,Russian,Entertainment,Belarus
29,El Reino Infantil,Yes,Spanish,Music,Argentina
30,Infobells - Hindi,Yes,Hindi,Education,India
31,ZAMZAM ELECTRONICS TRADING,No,Arabic,Entertainment,United Arab Emirates
32,UR Cristiano,No,"Portuguese, English","Entertainment,Sports",Portugal
33,Wave Music,Yes,Bhojpuri,Music,India
34,Toys and Colors,No,English,Entertainment,United States
35,Movieclips,Yes,English,Film,United States
36,Eminem Music,No,English,Music,United States
37,Sony Music India,Yes,Hindi,Music,India
38,YRF,Yes,Hindi,Music,India
39,Dude Perfect,No,English,Comedy,United States
40,Taylor Swift,No,English,Music,United States
41,HAR PAL GEO,Yes,Urdu,Entertainment,Pakistan
42,김프로KIMPRO,No,Korean,Entertainment,South Korea
43,Alan Chikin Chow,No,English,Entertainment,United States
44,LooLoo Kids,Yes,English,Music,Romania
45,Marshmello,No,English,Music,United States
46,ARY Digital HD,Yes,Urdu,Entertainment,Pakistan
47,BillionSurpriseToys,Yes,English,Entertainment,United States
48,Mark Rober,No,English,"Education,Entertainment",United States
49,Fede Vigevani,No,Spanish,Entertainment,Mexico
50,KL BRO Biju Rithvik,No,Hindi,Vlogging,India

In [43]:
#Save the cleaned DataFrame to a CSV file
top50_wiki.to_csv('cleaned_top50_wiki.csv', index=False)

In [44]:
top50_mydata = csv_dataframes['top50_channels.csv']

In [45]:
top50_mydata
#This df looks clean. Only data types will be handled.

,channelName,subscribers,views,totalVideos,playlistId
0,MrBeast,318000000,59678474940,818,UUX6OQ3DkcsbYNE6H8uQQuVA
1,T-Series,275000000,267733406150,21771,UUq-Fj5jknLsUf-MWSy4_brA
2,Cocomelon - Nursery Rhymes,183000000,188549400040,1280,UUbCmjCuTUZos6Inko4u57UQ
3,SET India,178000000,170110706792,145346,UUpEhnqL0y41EpW2TvWAHD7Q
4,✿ Kids Diana Show,126000000,106134359837,1256,UUk8GzjMOrta8yxDcKfylJYw
5,Vlad and Niki,125000000,95564400295,766,UUvlE5gTbOvjiolFlEm-c_Ow
6,Like Nastya,120000000,104953278452,904,UUJplp5SjeGSdVdwsfb9Q7lQ
7,PewDiePie,111000000,29402065856,4787,UU-lHJZR3Gqxm24_Vd_AJ5Yw
8,Zee Music Company,110000000,69776115748,12194,UUFFbwnve3yF62-tVXkTyHqg
9,WWE,104000000,88377408365,79228,UUJ5v_MCY6GNUBTO8-D3XoAg
10,Goldmines,100000000,29573446205,8853,UUyoXW-Dse7fURq30EWl_CUA
11,Sony SAB,95900000,120291452444,91550,UU6-F5tO8uklgE9Zy8IvbdFw
12,BLACKPINK,94900000,36756090437,603,UUOmHUn--16B90oW2L6FRR3A
13,ChuChu TV Nursery Rhymes & Kids Songs,93300000,52173851264,807,UUBnZ16ahKA2DZ_T5W0FPUXg
14,Stokes Twins,90300000,13671283034,321,UUbp9MyKCTEww4CxEzc_Tp0Q
15,Zee TV,84300000,94400703218,183695,UUppHT7SZKKvar4Oc9J4oljQ
16,5-Minute Crafts,80900000,27719241308,7266,UU295-Dw_tDNtZXFeAPAW6Aw
17,BANGTANTV,79000000,23675450062,2607,UULkAepWjdylmXSltofFvsYQ
18,Baby Shark - Pinkfong Kids’ Songs & Stories,77900000,46085560198,3322,UUcdwLMPsaU2ezNSJU1nFoBQ
19,Colors TV,76200000,74701875638,166466,UU55IWqFLDH1Xp7iu1_xknRA
20,HYBE LABELS,75700000,36060032414,2065,UU3IZKseVpdzPSBaWxBxundA
21,Justin Bieber,73600000,32963369076,249,UUIwFjwMjI0y7PDBVEO9-bkQ
22,T-Series Bhakti Sagar,70300000,35660314407,28686,UUaayLD9i5x4MmIoVZxXSv_g
23,Shemaroo Filmi Gaane,69600000,30047092213,8786,UUP6uH_XlsxrXwZQ4DlqbqPg
24,Tips Official,69000000,41285809659,6372,UUJrDMFOdv1I2k8n9oK_V21w
25,A4,67700000,30707073929,950,UU2tsySbe9TNrI-xh2lximHA
26,Aaj Tak,67500000,34066884821,394104,UUt4t-jeY85JegMlZ-E5UWtA
27,Canal KondZilla,67300000,38622573219,2894,UUffDXn7ycAzwL2LDlbyWOTw
28,El Reino Infantil,66100000,62390919454,1560,UUK1i2UviaXLUNrZlAFpw_jA
29,ZAMZAM ELECTRONICS TRADING,64800000,31488884098,18585,UUrnQFuUabBHaw-BRhPo8xEA
30,Infobells - Hindi,64700000,37980865691,707,UU1ciY6kR3yj3kaKZ6R7ewAg
31,UR · Cristiano,63500000,513745711,52,UUtxD0x6AuNNqdXO9Wp5GHew
32,Toys and Colors,63100000,74469548909,1330,UUgFXm4TI8htWmCyJ6cVPG_A
33,Wave Music,62900000,43439650082,20438,UU22nIfOTM7KLIQuFGMKzQbg
34,Movieclips,62200000,63345186001,41260,UU3gNmTGu-TTbFPpfSs5kNkg
35,EminemMusic,62000000,31281185723,196,UUfM3zsQsOnfWNUppiycmBuw
36,Sony Music India,61900000,31461049726,5455,UU56gTxNs4f9xZ7Pa2i5xNzg
37,YRF,61800000,43198153363,4228,UUbTLwN10NoCU4WDzLf1JMOA
38,Alan Chikin Chow,60500000,46127303037,1337,UU5gxP-2QqIh_09djvlm9Xcg
39,Dude Perfect,60400000,17762519430,451,UURijo3ddMTht_IHyNSNXpNQ
40,Taylor Swift,60000000,36912943387,274,UUqECaJ8Gagnn7YCbPEzWH6g
41,HAR PAL GEO,60000000,60049194850,144306,UUe9JSDmyqNgA_l2BzGHq1Ug
42,김프로KIMPRO,59900000,49287399382,3435,UUiVs2pnGW5mLIc1jS2nxhjg
43,LooLoo Kids - Nursery Rhymes and Children's Songs,58200000,35509509919,898,UU4NALVCmcmL5ntpV0thoH6w
44,ARY Digital HD,57500000,55923931625,148989,UU4JCksJF76g_MdzPVBJoC3Q
45,Marshmello,57400000,16062280232,491,UUEdvpU2pFRCVqU6yIPyTpMQ
46,Mark Rober,57300000,7653295743,174,UUY1kMZp36IQSyNx_9h4mpCg
47,Billion Surprise Toys,57300000,11976751968,1146,UURx3mKNUdl8QE06nEug7p6Q
48,Fede Vigevani,56700000,16083371492,1381,UUoQm-PeHC-cbJclKJYJ8LzA
49,KL BRO Biju Rithvik,56400000,47127899316,2746,UUL5nlHWXVLeOsSjKH2fhmsg

In [47]:
top50_mydata['subscribers'] = top50_mydata['subscribers'].astype(int)  
top50_mydata['views'] = top50_mydata['views'].astype(int) 
top50_mydata['totalVideos'] = top50_mydata['totalVideos'].astype(int)  
top50_mydata['channelName'] = top50_mydata['channelName'].astype(str)  
top50_mydata['playlistId'] = top50_mydata['playlistId'].astype(str)

In [48]:
top50_mydata.to_csv('cleaned_channeltop50_data.csv', index=False)

In [23]:
#Cocomelon Preprocess
cocomelon = csv_dataframes['UUbCmjCuTUZos6Inko4u57UQ_videos.csv']

In [24]:
cocomelon

,video_id,channelTitle,title,description,tags,publishedAt,viewCount,likeCount,favoriteCount,commentCount,duration,definition,caption,tags_count
0,YuMkDn2KNsU,Cocomelon - Nursery Rhymes,What's INSIDE the CoComelon?! Learn with @CoCo...,What could it BE inside the mysterious magic C...,"['cocomelon', 'abckidtv', 'nursery rhymes', 'c...",2024-09-29 07:00:21,165326,4543.0,0,0,PT40S,hd,false,33
1,OucUfmLncxo,Cocomelon - Nursery Rhymes,Bath Songs for Bath Time with Sea Animals! | C...,JJ and TomTom stage a heroic rescue with their...,"['JJ', 'abckidtv', 'baby songs', 'children son...",2024-09-28 07:00:18,239212,1039.0,0,0,PT5M51S,hd,false,39
2,gXm2-GxnEwc,Cocomelon - Nursery Rhymes,Easy CoComelon Halloween Crafts! DIY Dino Cost...,It's time for some tabletop HALLOWEEN CRAFTS w...,"['cocomelon', 'abckidtv', 'nursery rhymes', 'c...",2024-09-27 07:00:26,988863,19545.0,0,0,PT15S,hd,false,35
3,7u3FRvWj-G0,Cocomelon - Nursery Rhymes,Halloween Pumpkin Craft Song | CoComelon Nurse...,"Cody crafts a special Halloween pumpkin, thank...","['JJ', 'abckidtv', 'baby songs', 'children son...",2024-09-27 07:00:09,415289,1571.0,0,0,PT2M52S,hd,false,33
4,8sWurm5nKsI,Cocomelon - Nursery Rhymes,"🔴LIVE CoComelon Food Songs, Fruits, Apples, Ba...",Subscribe for new videos every week!\nhttps://...,"['cocomelon', 'abckidtv', 'nursery rhymes', 'c...",2024-09-26 12:52:14,5681849,NaN,0,0,P0D,sd,false,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1278,tVpgEiBcw7M,Cocomelon - Nursery Rhymes,"Learn the ABCs: ""P"" is for Pig and Penguin","Featuring the letter ""P""! \nThis series goes t...","['baby songs', 'sing-along', 'abckidtv', 'pres...",2007-06-20 03:41:46,10733206,5804.0,0,0,PT1M31S,sd,false,15
1279,7W6fEFixi5U,Cocomelon - Nursery Rhymes,"Learn the ABCs: ""L"" is for Lion and Ladybug","Featuring the letter ""L""! \nThis series goes t...","['baby songs', 'kids education', 'kindergarten...",2007-06-20 03:34:33,25980367,21746.0,0,0,PT1M48S,sd,false,15
1280,cgC8BC1OINQ,Cocomelon - Nursery Rhymes,"Learn the ABCs: ""K"" is for Kangaroo","Featuring the letter ""K""! \nThis series goes t...","['cocomelon', 'kids entertainment', 'kindergar...",2007-06-20 01:31:32,9480926,4981.0,0,0,PT2M13S,sd,false,15
1281,0fw3l1z9CUQ,Cocomelon - Nursery Rhymes,ABC Song with Cute Ending,This ABC Song is one of the most popular ABC s...,"['toddler', 'children songs', 'abckidtv', 'kid...",2006-09-02 01:34:53,303469834,333172.0,0,0,PT45S,sd,false,15
1282,yfZ29cVaaVQ,Cocomelon - Nursery Rhymes,ABC Song,A fast and funny song sung by a child and gran...,"['kids animation', 'baby songs', 'children son...",2006-09-01 23:39:09,31139121,44608.0,0,0,PT30S,sd,false,15

In [5]:
#Handling data-time in publishedAt column
cocomelon['publishedAt'] = pd.to_datetime(cocomelon['publishedAt'])
cocomelon['publishedAt'] = cocomelon['publishedAt'].dt.tz_localize(None)

In [6]:
#Convert numeric columns
numeric_columns = ['viewCount', 'likeCount', 'favoriteCount', 'commentCount']
cocomelon[numeric_columns] = cocomelon[numeric_columns].apply(pd.to_numeric, errors='coerce')

In [7]:
import ast

In [8]:
#Function to count the number of tags 
def count_tags(tags_str):
    try:
        tags_list = ast.literal_eval(tags_str)
        if isinstance(tags_list, list):
            return len(tags_list)
        else:
            return 0
    except (ValueError, SyntaxError):
        #If the string is not a valid list, return 0
        return 0

In [9]:
cocomelon['tags_count'] = cocomelon['tags'].apply(count_tags)

In [10]:
columns = list(cocomelon.columns)

#Finding the index of tags column and positioning in the initial place
tags_index = columns.index('tags')

#Drop the original 'tags' column
cocomelon = cocomelon.drop('tags', axis=1)

#Insert the 'tags_count' column in the original position of 'tags'
columns[tags_index] = 'tags_count'

cocomelon = cocomelon[columns]

In [11]:
pip install isodate

Requirement already satisfied: isodate in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (0.6.1)
Requirement already satisfied: six in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from isodate) (1.16.0)

[notice] A new release of pip is available: 23.3.1 -> 24.2
[notice] To update, run: pip3.9 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [12]:
import isodate

In [13]:
#Converting duration column from ISO 8601 to minutes
cocomelon['duration'] = cocomelon['duration'].apply(lambda x: isodate.parse_duration(x).total_seconds() / 60)

In [16]:
cocomelon.isnull().any()

video_id         False
channelTitle     False
title            False
description      False
tags_count       False
publishedAt      False
viewCount        False
likeCount         True
favoriteCount    False
commentCount     False
duration         False
definition       False
caption          False
tags_count       False
dtype: bool

In [14]:
cocomelon

,video_id,channelTitle,title,description,tags_count,publishedAt,viewCount,likeCount,favoriteCount,commentCount,duration,definition,caption,tags_count
0,YuMkDn2KNsU,Cocomelon - Nursery Rhymes,What's INSIDE the CoComelon?! Learn with @CoCo...,What could it BE inside the mysterious magic C...,33,2024-09-29 07:00:21,165326,4543.0,0,0,0.666667,hd,false,33
1,OucUfmLncxo,Cocomelon - Nursery Rhymes,Bath Songs for Bath Time with Sea Animals! | C...,JJ and TomTom stage a heroic rescue with their...,39,2024-09-28 07:00:18,239212,1039.0,0,0,5.850000,hd,false,39
2,gXm2-GxnEwc,Cocomelon - Nursery Rhymes,Easy CoComelon Halloween Crafts! DIY Dino Cost...,It's time for some tabletop HALLOWEEN CRAFTS w...,35,2024-09-27 07:00:26,988863,19545.0,0,0,0.250000,hd,false,35
3,7u3FRvWj-G0,Cocomelon - Nursery Rhymes,Halloween Pumpkin Craft Song | CoComelon Nurse...,"Cody crafts a special Halloween pumpkin, thank...",33,2024-09-27 07:00:09,415289,1571.0,0,0,2.866667,hd,false,33
4,8sWurm5nKsI,Cocomelon - Nursery Rhymes,"🔴LIVE CoComelon Food Songs, Fruits, Apples, Ba...",Subscribe for new videos every week!\nhttps://...,24,2024-09-26 12:52:14,5681849,NaN,0,0,0.000000,sd,false,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1278,tVpgEiBcw7M,Cocomelon - Nursery Rhymes,"Learn the ABCs: ""P"" is for Pig and Penguin","Featuring the letter ""P""! \nThis series goes t...",15,2007-06-20 03:41:46,10733206,5804.0,0,0,1.516667,sd,false,15
1279,7W6fEFixi5U,Cocomelon - Nursery Rhymes,"Learn the ABCs: ""L"" is for Lion and Ladybug","Featuring the letter ""L""! \nThis series goes t...",15,2007-06-20 03:34:33,25980367,21746.0,0,0,1.800000,sd,false,15
1280,cgC8BC1OINQ,Cocomelon - Nursery Rhymes,"Learn the ABCs: ""K"" is for Kangaroo","Featuring the letter ""K""! \nThis series goes t...",15,2007-06-20 01:31:32,9480926,4981.0,0,0,2.216667,sd,false,15
1281,0fw3l1z9CUQ,Cocomelon - Nursery Rhymes,ABC Song with Cute Ending,This ABC Song is one of the most popular ABC s...,15,2006-09-02 01:34:53,303469834,333172.0,0,0,0.750000,sd,false,15
1282,yfZ29cVaaVQ,Cocomelon - Nursery Rhymes,ABC Song,A fast and funny song sung by a child and gran...,15,2006-09-01 23:39:09,31139121,44608.0,0,0,0.500000,sd,false,15

In [17]:
cocomelon.to_csv('cleaned_cocomelon.csv', index=False)

In [41]:
#T-series Preprocess
tseries = csv_dataframes['UUq-Fj5jknLsUf-MWSy4_brA_videos.csv']

In [42]:
tseries.head(10)

,video_id,channelTitle,title,description,tags,publishedAt,viewCount,likeCount,favoriteCount,commentCount,duration,definition,caption,tags_count
0,MhD8tHrKQOU,T-Series,Rajkummar and Triptii's Chemistry😍😍 | Mere Meh...,NaN,"['hindi songs new', 'tseries', 'tseries songs'...",2024-09-29 14:00:11,223247.0,7826.0,0.0,83.0,PT38S,hd,false,20
1,bZ3fy558Z54,T-Series,"""Yeh Padhai Nahi Dhanda Hai"" | Hindi Medium (M...",Presenting the movie clip of the Bollywood mov...,"['hindi songs 2024', 'bollywood songs 2024', '...",2024-09-29 11:30:33,58691.0,992.0,0.0,88.0,PT7M15S,hd,false,20
2,x2btnrM5SIA,T-Series,"""Bacchi Ke Liye Jhooth Bola"" | Irrfan Khan, Sa...",Presenting the movie clip of the Bollywood mov...,"['hindi songs 2024', 'hindi songs new', 'bolly...",2024-09-29 11:30:23,79540.0,1184.0,0.0,27.0,PT12M16S,hd,false,19
3,MnkRJ2Ygtb4,T-Series,"""Raj Ne Kholi ATM Machine!!"" | Irrfan Khan, Sa...",Presenting the movie clip of the Bollywood mov...,"['hindi songs 2024', 'hindi songs new', 'bolly...",2024-09-29 11:30:15,79881.0,1525.0,0.0,122.0,PT14M18S,hd,false,20
4,4FJs7EGp2ME,T-Series,Making of Tum Jo Mile Ho | Rajkummar Rao | Tri...,"Presenting the Making of the First Song ""Tum J...","['hindi songs new', 'bollywood movies 2024', '...",2024-09-29 09:32:29,76520.0,1915.0,0.0,90.0,PT1M45S,hd,false,19
5,9tf89c0xTc4,T-Series,YO YO HONEY SINGH BEAT KARE BAPTIZE🔥| HIGH ON ...,NaN,"['yo yo honey singh beat kare baptize', 'yo yo...",2024-09-29 07:40:33,30744.0,2711.0,0.0,53.0,PT28S,hd,false,18
6,ALsAT1bMMqY,T-Series,"Galliyan (Club Dance Mix) | Siddharth M, Shrad...","Presenting ""Galliyan (Club Dance Mix)"" by DJ M...","['hindi songs new', 'bollywood songs 2024', 'b...",2024-09-29 05:31:07,68785.0,2946.0,0.0,262.0,PT3M52S,hd,false,23
7,-uLJ-XCnWRE,T-Series,"Maa Ka Mann: Vishal Mishra, Manoj Muntashir | ...","Presenting the Divine Bhajan ""Maa Ka Mann"", Su...","['hindi songs new', 'bollywood songs 2024', 'b...",2024-09-28 18:40:09,7.0,33891.0,0.0,2952.0,NaN,hd,false,19
8,xPON0USOkAY,T-Series,"""Paani Nahi Bharne Doge?"" | Irrfan Khan, Saba ...",Presenting the movie clip of the Bollywood mov...,"['hindi songs 2024', 'hindi songs new', 'bolly...",2024-09-28 14:30:14,159757.0,1572.0,0.0,125.0,PT8M18S,hd,false,21
9,5uxLEgnQHEQ,T-Series,"""Yeh Hai Dengue Chikungunya!"" Irrfan Khan, Dee...",Presenting the movie clip of the Bollywood mov...,"['hindi songs 2024', 'hindi songs new', 'bolly...",2024-09-28 14:30:04,159403.0,2348.0,0.0,167.0,PT8M55S,hd,false,19

In [43]:
tseries['publishedAt'] = pd.to_datetime(tseries['publishedAt'], errors='coerce')

In [44]:

tseries['publishedAt'] = tseries['publishedAt'].dt.tz_localize(None)

In [45]:
tseries[numeric_columns] = tseries[numeric_columns].apply(pd.to_numeric, errors='coerce')

In [46]:
tseries['tags_count'] = tseries['tags'].apply(count_tags)

columns = list(tseries.columns)

#Finding the index of tags column and positioning in the initial place
tags_index = columns.index('tags')

#Drop the original 'tags' column
tseries = tseries.drop('tags', axis=1)

#Inserting the 'tags_count' column in the original position of 'tags'
columns[tags_index] = 'tags_count'

tseries = tseries[columns]

In [47]:
import numpy as np

In [48]:
#Some rows gave error because of the invalid strings in duration column.
#This code identifies the rows with invalid duration and replaces them with NaN
#and converts the valid durations to second
invalid_duration_rows = []


def safe_parse_duration(x, idx):
    try:
        return isodate.parse_duration(x).total_seconds() / 60
    except (isodate.ISO8601Error, ValueError, TypeError):
        # If there's an error, log the index of the invalid row
        invalid_duration_rows.append(idx)
        return np.nan  


tseries['duration'] = tseries.apply(lambda row: safe_parse_duration(row['duration'], row.name), axis=1)


print("Rows with invalid durations:", invalid_duration_rows)

Rows with invalid durations: [7, 8055, 8056, 8066, 8067, 8068, 8084, 8085]

In [52]:
print(tseries.isnull().any())

video_id         False
channelTitle      True
title             True
description       True
tags_count       False
publishedAt       True
viewCount         True
likeCount         True
favoriteCount     True
commentCount      True
duration          True
definition        True
caption           True
tags_count       False
dtype: bool

In [81]:
nan_counts = tseries.isna().sum()

print(nan_counts)

video_id           0
channelTitle       1
title              1
description      386
tags_count         0
publishedAt        7
viewCount          4
likeCount         18
favoriteCount      7
commentCount      23
duration           8
definition         7
caption            7
tags_count         0
dtype: int64

In [56]:
tseries.head(10)

,video_id,channelTitle,title,description,tags_count,publishedAt,viewCount,likeCount,favoriteCount,commentCount,duration,definition,caption,tags_count
0,MhD8tHrKQOU,T-Series,Rajkummar and Triptii's Chemistry😍😍 | Mere Meh...,NaN,20,2024-09-29 14:00:11,223247.0,7826.0,0.0,83.0,0.633333,hd,false,20
1,bZ3fy558Z54,T-Series,"""Yeh Padhai Nahi Dhanda Hai"" | Hindi Medium (M...",Presenting the movie clip of the Bollywood mov...,20,2024-09-29 11:30:33,58691.0,992.0,0.0,88.0,7.250000,hd,false,20
2,x2btnrM5SIA,T-Series,"""Bacchi Ke Liye Jhooth Bola"" | Irrfan Khan, Sa...",Presenting the movie clip of the Bollywood mov...,19,2024-09-29 11:30:23,79540.0,1184.0,0.0,27.0,12.266667,hd,false,19
3,MnkRJ2Ygtb4,T-Series,"""Raj Ne Kholi ATM Machine!!"" | Irrfan Khan, Sa...",Presenting the movie clip of the Bollywood mov...,20,2024-09-29 11:30:15,79881.0,1525.0,0.0,122.0,14.300000,hd,false,20
4,4FJs7EGp2ME,T-Series,Making of Tum Jo Mile Ho | Rajkummar Rao | Tri...,"Presenting the Making of the First Song ""Tum J...",19,2024-09-29 09:32:29,76520.0,1915.0,0.0,90.0,1.750000,hd,false,19
5,9tf89c0xTc4,T-Series,YO YO HONEY SINGH BEAT KARE BAPTIZE🔥| HIGH ON ...,NaN,18,2024-09-29 07:40:33,30744.0,2711.0,0.0,53.0,0.466667,hd,false,18
6,ALsAT1bMMqY,T-Series,"Galliyan (Club Dance Mix) | Siddharth M, Shrad...","Presenting ""Galliyan (Club Dance Mix)"" by DJ M...",23,2024-09-29 05:31:07,68785.0,2946.0,0.0,262.0,3.866667,hd,false,23
7,-uLJ-XCnWRE,T-Series,"Maa Ka Mann: Vishal Mishra, Manoj Muntashir | ...","Presenting the Divine Bhajan ""Maa Ka Mann"", Su...",19,2024-09-28 18:40:09,7.0,33891.0,0.0,2952.0,NaN,hd,false,19
8,xPON0USOkAY,T-Series,"""Paani Nahi Bharne Doge?"" | Irrfan Khan, Saba ...",Presenting the movie clip of the Bollywood mov...,21,2024-09-28 14:30:14,159757.0,1572.0,0.0,125.0,8.300000,hd,false,21
9,5uxLEgnQHEQ,T-Series,"""Yeh Hai Dengue Chikungunya!"" Irrfan Khan, Dee...",Presenting the movie clip of the Bollywood mov...,19,2024-09-28 14:30:04,159403.0,2348.0,0.0,167.0,8.916667,hd,false,19

In [57]:
tseries.to_csv('cleaned_tseries.csv', index=False)

In [60]:
mrbeast = csv_dataframes['UUX6OQ3DkcsbYNE6H8uQQuVA_videos.csv']

In [61]:
mrbeast

,video_id,channelTitle,title,description,tags,publishedAt,viewCount,likeCount,favoriteCount,commentCount,duration,definition,caption
0,vDrSCXFMAKk,MrBeast,"Spot The Difference, Win $10,000",NaN,NaN,2024-09-28T20:00:00Z,17635239,1117393,0,1606,PT58S,hd,false
1,snX5YyflrGw,MrBeast,"100 Identical Twins Fight For $250,000",I’ve never seen this many twins in one place b...,NaN,2024-09-28T16:00:00Z,45970533,1790265,0,16538,PT35M40S,hd,true
2,nbzQdlWrcnk,MrBeast,Running With Bigger And Bigger Lunchlys,NaN,NaN,2024-09-20T16:00:00Z,111482011,4095255,0,6936,PT18S,hd,false
3,8krJy31Diow,MrBeast,Holding Bigger And Bigger Dogs,NaN,NaN,2024-09-16T18:00:00Z,55764303,3167371,0,4803,PT18S,hd,false
4,aRcUVhVlSHg,MrBeast,"Men Vs Women Survive The Wilderness For $500,000",Some of these strategies were wild!\nWet thing...,NaN,2024-09-07T16:00:00Z,109280250,3443703,0,49032,PT31M48S,hd,true
...,...,...,...,...,...,...,...,...,...,...,...,...,...
813,7qj3nuF9Dzw,MrBeast,Most Epic minecraft skin EVER (Psy),Psy in minecraft!!! drop a like for psy's mo...,"['psy', 'minecraft', 'epic', 'skin', 'most', '...",2013-01-13T01:59:21Z,1072340,40661,0,3592,PT31S,hd,false
814,Y74b7WlcEpk,MrBeast,More birds IN MINECRAFT!!,Basically what this mod does is adds more bird...,"['birds', 'minecraft', 'in', 'more', 'must', '...",2013-01-12T23:35:45Z,1216455,45889,0,3782,PT2M6S,hd,false
815,Z8nEEdXTaX0,MrBeast,Boxy item mod Minecraft. EPIC,At the begining i said i was mrbeast6000.... i...,"['boxy', 'item', 'mod', 'minecraft', 'epic']",2013-01-12T22:34:11Z,1433755,54143,0,4269,PT1M30S,hd,false
816,jP82d277Cc8,MrBeast,Harry Potter Mod In Minecraft! EPIC MUST SEE M...,One of the coolest mods i have ever seen\n\nMo...,"['Harry Potter minecraft', 'minecraft', 'minec...",2012-03-09T23:29:03Z,5299063,NaN,0,9285,PT3M59S,hd,false
817,2XVcLrB7B3Y,MrBeast,Worst Minecraft Saw Trap Ever???,This is the worst saw trap ever done in minecr...,"['minecraft', 'saw trap', 'minecraft saw trap'...",2012-02-20T22:42:32Z,26817527,1206897,0,131622,PT2M37S,hd,false

In [67]:
#Tags column includes some NaN values. The previous count_tags function should be modified to replace NaN with 0

def count_tags(tags_str):
    #Check if the value is NaN, return 0 in that case
    if pd.isna(tags_str):
        return 0
    try:
        tags_list = ast.literal_eval(tags_str)
        if isinstance(tags_list, list):
            return len(tags_list)
        else:
            return 0
    except (ValueError, SyntaxError):
        return 0

In [68]:
mrbeast[numeric_columns] = mrbeast[numeric_columns].apply(pd.to_numeric, errors='coerce')

In [69]:
mrbeast['tags_count'] = mrbeast['tags'].apply(count_tags)

columns = list(mrbeast.columns)

#Finding the index of tags column and positioning in the initial place
tags_index = columns.index('tags')

#Drop the original 'tags' column
mrbeast = mrbeast.drop('tags', axis=1)

#Inserting the 'tags_count' column in the original position of 'tags'
columns[tags_index] = 'tags_count'

mrbeast = mrbeast[columns]

In [71]:
mrbeast['publishedAt'] = pd.to_datetime(mrbeast['publishedAt'], errors='coerce')
mrbeast['publishedAt'] = mrbeast['publishedAt'].dt.tz_localize(None)

In [72]:
mrbeast

,video_id,channelTitle,title,description,tags_count,publishedAt,viewCount,likeCount,favoriteCount,commentCount,duration,definition,caption,tags_count
0,vDrSCXFMAKk,MrBeast,"Spot The Difference, Win $10,000",NaN,0,2024-09-28 20:00:00,17635239,1117393.0,0,1606.0,PT58S,hd,false,0
1,snX5YyflrGw,MrBeast,"100 Identical Twins Fight For $250,000",I’ve never seen this many twins in one place b...,0,2024-09-28 16:00:00,45970533,1790265.0,0,16538.0,PT35M40S,hd,true,0
2,nbzQdlWrcnk,MrBeast,Running With Bigger And Bigger Lunchlys,NaN,0,2024-09-20 16:00:00,111482011,4095255.0,0,6936.0,PT18S,hd,false,0
3,8krJy31Diow,MrBeast,Holding Bigger And Bigger Dogs,NaN,0,2024-09-16 18:00:00,55764303,3167371.0,0,4803.0,PT18S,hd,false,0
4,aRcUVhVlSHg,MrBeast,"Men Vs Women Survive The Wilderness For $500,000",Some of these strategies were wild!\nWet thing...,0,2024-09-07 16:00:00,109280250,3443703.0,0,49032.0,PT31M48S,hd,true,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813,7qj3nuF9Dzw,MrBeast,Most Epic minecraft skin EVER (Psy),Psy in minecraft!!! drop a like for psy's mo...,6,2013-01-13 01:59:21,1072340,40661.0,0,3592.0,PT31S,hd,false,6
814,Y74b7WlcEpk,MrBeast,More birds IN MINECRAFT!!,Basically what this mod does is adds more bird...,7,2013-01-12 23:35:45,1216455,45889.0,0,3782.0,PT2M6S,hd,false,7
815,Z8nEEdXTaX0,MrBeast,Boxy item mod Minecraft. EPIC,At the begining i said i was mrbeast6000.... i...,5,2013-01-12 22:34:11,1433755,54143.0,0,4269.0,PT1M30S,hd,false,5
816,jP82d277Cc8,MrBeast,Harry Potter Mod In Minecraft! EPIC MUST SEE M...,One of the coolest mods i have ever seen\n\nMo...,6,2012-03-09 23:29:03,5299063,NaN,0,9285.0,PT3M59S,hd,false,6
817,2XVcLrB7B3Y,MrBeast,Worst Minecraft Saw Trap Ever???,This is the worst saw trap ever done in minecr...,4,2012-02-20 22:42:32,26817527,1206897.0,0,131622.0,PT2M37S,hd,false,4

In [73]:
mrbeast[numeric_columns] = mrbeast[numeric_columns].apply(pd.to_numeric, errors='coerce')

In [74]:
mrbeast

,video_id,channelTitle,title,description,tags_count,publishedAt,viewCount,likeCount,favoriteCount,commentCount,duration,definition,caption,tags_count
0,vDrSCXFMAKk,MrBeast,"Spot The Difference, Win $10,000",NaN,0,2024-09-28 20:00:00,17635239,1117393.0,0,1606.0,PT58S,hd,false,0
1,snX5YyflrGw,MrBeast,"100 Identical Twins Fight For $250,000",I’ve never seen this many twins in one place b...,0,2024-09-28 16:00:00,45970533,1790265.0,0,16538.0,PT35M40S,hd,true,0
2,nbzQdlWrcnk,MrBeast,Running With Bigger And Bigger Lunchlys,NaN,0,2024-09-20 16:00:00,111482011,4095255.0,0,6936.0,PT18S,hd,false,0
3,8krJy31Diow,MrBeast,Holding Bigger And Bigger Dogs,NaN,0,2024-09-16 18:00:00,55764303,3167371.0,0,4803.0,PT18S,hd,false,0
4,aRcUVhVlSHg,MrBeast,"Men Vs Women Survive The Wilderness For $500,000",Some of these strategies were wild!\nWet thing...,0,2024-09-07 16:00:00,109280250,3443703.0,0,49032.0,PT31M48S,hd,true,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813,7qj3nuF9Dzw,MrBeast,Most Epic minecraft skin EVER (Psy),Psy in minecraft!!! drop a like for psy's mo...,6,2013-01-13 01:59:21,1072340,40661.0,0,3592.0,PT31S,hd,false,6
814,Y74b7WlcEpk,MrBeast,More birds IN MINECRAFT!!,Basically what this mod does is adds more bird...,7,2013-01-12 23:35:45,1216455,45889.0,0,3782.0,PT2M6S,hd,false,7
815,Z8nEEdXTaX0,MrBeast,Boxy item mod Minecraft. EPIC,At the begining i said i was mrbeast6000.... i...,5,2013-01-12 22:34:11,1433755,54143.0,0,4269.0,PT1M30S,hd,false,5
816,jP82d277Cc8,MrBeast,Harry Potter Mod In Minecraft! EPIC MUST SEE M...,One of the coolest mods i have ever seen\n\nMo...,6,2012-03-09 23:29:03,5299063,NaN,0,9285.0,PT3M59S,hd,false,6
817,2XVcLrB7B3Y,MrBeast,Worst Minecraft Saw Trap Ever???,This is the worst saw trap ever done in minecr...,4,2012-02-20 22:42:32,26817527,1206897.0,0,131622.0,PT2M37S,hd,false,4

In [76]:
mrbeast['duration'] = mrbeast['duration'].apply(lambda x: isodate.parse_duration(x).total_seconds() / 60)

In [77]:
mrbeast

,video_id,channelTitle,title,description,tags_count,publishedAt,viewCount,likeCount,favoriteCount,commentCount,duration,definition,caption,tags_count
0,vDrSCXFMAKk,MrBeast,"Spot The Difference, Win $10,000",NaN,0,2024-09-28 20:00:00,17635239,1117393.0,0,1606.0,0.966667,hd,false,0
1,snX5YyflrGw,MrBeast,"100 Identical Twins Fight For $250,000",I’ve never seen this many twins in one place b...,0,2024-09-28 16:00:00,45970533,1790265.0,0,16538.0,35.666667,hd,true,0
2,nbzQdlWrcnk,MrBeast,Running With Bigger And Bigger Lunchlys,NaN,0,2024-09-20 16:00:00,111482011,4095255.0,0,6936.0,0.300000,hd,false,0
3,8krJy31Diow,MrBeast,Holding Bigger And Bigger Dogs,NaN,0,2024-09-16 18:00:00,55764303,3167371.0,0,4803.0,0.300000,hd,false,0
4,aRcUVhVlSHg,MrBeast,"Men Vs Women Survive The Wilderness For $500,000",Some of these strategies were wild!\nWet thing...,0,2024-09-07 16:00:00,109280250,3443703.0,0,49032.0,31.800000,hd,true,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813,7qj3nuF9Dzw,MrBeast,Most Epic minecraft skin EVER (Psy),Psy in minecraft!!! drop a like for psy's mo...,6,2013-01-13 01:59:21,1072340,40661.0,0,3592.0,0.516667,hd,false,6
814,Y74b7WlcEpk,MrBeast,More birds IN MINECRAFT!!,Basically what this mod does is adds more bird...,7,2013-01-12 23:35:45,1216455,45889.0,0,3782.0,2.100000,hd,false,7
815,Z8nEEdXTaX0,MrBeast,Boxy item mod Minecraft. EPIC,At the begining i said i was mrbeast6000.... i...,5,2013-01-12 22:34:11,1433755,54143.0,0,4269.0,1.500000,hd,false,5
816,jP82d277Cc8,MrBeast,Harry Potter Mod In Minecraft! EPIC MUST SEE M...,One of the coolest mods i have ever seen\n\nMo...,6,2012-03-09 23:29:03,5299063,NaN,0,9285.0,3.983333,hd,false,6
817,2XVcLrB7B3Y,MrBeast,Worst Minecraft Saw Trap Ever???,This is the worst saw trap ever done in minecr...,4,2012-02-20 22:42:32,26817527,1206897.0,0,131622.0,2.616667,hd,false,4

In [78]:
mrbeast.isnull().any()

video_id         False
channelTitle     False
title            False
description       True
tags_count       False
publishedAt      False
viewCount        False
likeCount         True
favoriteCount    False
commentCount      True
duration         False
definition       False
caption          False
tags_count       False
dtype: bool

In [79]:
mrbeast.to_csv('cleaned_mrbeast.csv', index=False)